---
- name: Create Kubernetes Namespace if it does not exist
  hosts: localhost
  tasks:
    - name: Ensure Kubernetes Namespace exists
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: nodejs-application-namespace
    

- name: Deploy Docker Containers as Kubernetes Pods
  hosts: localhost
  tasks:
    - name: Apply Deployment Manifests
      k8s:
        state: present
        definition: "{{ lookup('file', './my-app-deployment.yaml') }}"
