---
- name: Provision Minikube Cluster
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install Minikube dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - apt-transport-https
        - virtualbox # or your preferred VM driver for Minikube

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      package:
        name: docker-ce
        state: present
    
    - name: Start Minikube
      command: minikube start 